mob_type_name = {
    # Nombres de mobs (art masculino)
    "zombie": "Zombie",
    "skeleton": "Esqueleto",
    "creeper": "Creeper",
    "enderman": "Enderman",
    "slime": "Slime",
    "ghast": "Ghast",
    "blaze": "Blaze",
    "guardian": "Guardian",
    "shulker": "Shulker",
    "pig": "Cerdo",
    "horse": "Caballo",
    "wolf": "Lobo",
    "cat": "Gato",
    "parrot": "Loro",
    "rabbit": "Conejo",
    "fox": "Zorro",
    "panda": "Panda",
    "dolphin": "Delfín",
    "axolotl": "Ajolote",
    "villager": "Aldeano",
    "iron_golem": "Gólem de hierro",
    "snow_golem": "Gólem de nieve",
    "wither_skeleton": "Esqueleto Wither",
    "phantom": "Fantasma",
    "stray": "Stray",
    "drowned": "Ahogado",
    "zombified_piglin": "Piglin zombificado",
    "piglin": "Piglin",
    "hoglin": "Hoglin",
    "zoglin": "Zoglin",
    "warden": "Warden",
    "allay": "Allay",
    "camel": "Camello",
    "sniffer": "Sniffer",
    "tadpole": "Renacuajo",
    # Nombres de mobs (art femenino)
    "witch": "Bruja",
    "chicken": "Gallina",
    "cow": "Vaca",
    "sheep": "Oveja",
    "turtle": "Tortuga",
    "bee": "Abeja",
    "goat": "Cabra",
    "frog": "Rana",
    "spider": "Araña",
}

articles_by_mob_type: dict[str, str] = {
    "zombie": "un",
    "skeleton": "un",
    "creeper": "un",
    "enderman": "un",
    "slime": "un",
    "ghast": "un",
    "blaze": "un",
    "guardian": "un",
    "shulker": "un",
    "pig": "un",
    "horse": "un",
    "wolf": "un",
    "cat": "un",
    "parrot": "un",
    "rabbit": "un",
    "fox": "un",
    "panda": "un",
    "dolphin": "un",
    "axolotl": "un",
    "villager": "un",
    "iron_golem": "un",
    "snow_golem": "un",
    "wither_skeleton": "un",
    "phantom": "un",
    "stray": "un",
    "drowned": "un",
    "zombified_piglin": "un",
    "piglin": "un",
    "hoglin": "un",
    "zoglin": "un",
    "warden": "un",
    "allay": "un",
    "camel": "un",
    "sniffer": "un",
    "tadpole": "un",
    "witch": "una",
    "chicken": "una",
    "cow": "una",
    "sheep": "una",
    "turtle": "una",
    "bee": "una",
    "goat": "una",
    "frog": "una",
    "spider": "una",
}

colors_by_code: dict[str, str] = {
    '§0': "Negro",
    '§1': "Azul oscuro",
    '§2': "Verde oscuro",
    '§3': "Agua marina",
    '§4': "Rojo oscuro",
    '§5': "Púrpura",
    '§6': "Oro",
    '§7': "Gris claro",
    '§8': "Gris oscuro",
    '§9': "Azul claro",
    '§a': "Verde claro",
    '§b': "Aguamarina",
    '§c': "Rojo Claro",
    '§d': "Rosa",
    '§e': "Amarillo",
    '§f': "Blanco",
}
