# config/const.py
mob_type_name = {
    "bogged": "Enfangado",
    "breeze": "Brisa",
    "blaze": "Blaze",
    "cave_spider": "Araña de cueva",
    "creaking": "Creaking",
    "creeper": "Creeper",
    "drowned": "Ahogado",
    "enderman": "Enderman",
    "endermite": "Endermite",
    "evocation_illager": "Evocador",
    "ghast": "Ghast",
    "guardian": "Guardian",
    "hoglin": "Hoglin",
    "husk": "Husk",
    "magma_cube": "Cubo de magma",
    "piglin": "Piglin",
    "piglin_brute": "Piglin Bruto",
    "pillager": "Pillager",
    "phantom": "Fantasma",
    "ravager": "Ravager",
    "shulker": "Shulker",
    "silverfish": "Silverfish",
    "skeleton": "Esqueleto",
    "slime": "Slime",
    "spider": "Araña",
    "stray": "Stray",
    "vex": "Vex",
    "vindicator": "Vindicador",
    "witch": "Bruja",
    "wither_skeleton": "Esqueleto Wither",
    "zoglin": "Zoglin",
    "zombie": "Zombie",
    "zombie_villager": "Aldeano Zombificado",
    "allay": "Allay",
    "armadillo": "Armadillo",
    "axolotl": "Ajolote",
    "bat": "Murciélago",
    "bee": "Abeja",
    "camel": "Camello",
    "cat": "Gato",
    "chicken": "Gallina",
    "cow": "Vaca",
    "donkey": "Burro",
    "fox": "Zorro",
    "frog": "Rana",
    "goat": "Cabra",
    "horse": "Caballo",
    "llama": "Llama",
    "mooshroom": "Chapivaca",
    "mule": "Mula",
    "panda": "Panda",
    "parrot": "Loro",
    "pig": "Cerdo",
    "rabbit": "Conejo",
    "sheep": "Oveja",
    "sniffer": "Sniffer",
    "strider": "Strider",
    "turtle": "Tortuga",
    "wolf": "Lobo",
    "lightning_bolt": "Rayo",
    "wind_charge_projectile": "Proyectil de carga de viento",
    "wither": "Wither",
    "warden": "Warden",
    "elder_guardian": "Guardia anciano",
}

articles_by_mob_type: dict[str, str] = {
    "bogged": "un",
    "breeze": "un",
    "blaze": "un",
    "cave_spider": "una",
    "creaking": "un",
    "creeper": "un",
    "drowned": "un",
    "enderman": "un",
    "endermite": "un",
    "evocation_illager": "un",
    "ghast": "un",
    "guardian": "un",
    "hoglin": "un",
    "husk": "un",
    "magma_cube": "un",
    "piglin": "un",
    "piglin_brute": "un",
    "pillager": "un",
    "phantom": "un",
    "ravager": "un",
    "shulker": "un",
    "silverfish": "un",
    "skeleton": "un",
    "slime": "un",
    "spider": "una",
    "stray": "un",
    "vex": "un",
    "vindicator": "un",
    "witch": "una",
    "wither_skeleton": "un",
    "zoglin": "un",
    "zombie": "un",
    "zombie_villager": "un",
    "allay": "un",
    "armadillo": "un",
    "axolotl": "un",
    "bat": "un",
    "bee": "una",
    "camel": "un",
    "cat": "un",
    "chicken": "una",
    "cow": "una",
    "donkey": "un",
    "fox": "un",
    "frog": "una",
    "goat": "una",
    "horse": "un",
    "llama": "una",
    "mooshroom": "una",
    "mule": "una",
    "panda": "un",
    "parrot": "un",
    "pig": "un",
    "rabbit": "un",
    "sheep": "una",
    "sniffer": "un",
    "strider": "un",
    "turtle": "una",
    "wolf": "un",
    "lightning_bolt": "un",
    "wind_charge_projectile": "un",
    "wither": "un",
    "warden": "un",
    "elder_guardian": "un",
}

colors_by_code: dict[str, str] = {
    '§0': "Negro",
    '§1': "Azul oscuro",
    '§2': "Verde oscuro",
    '§3': "Agua marina",
    '§4': "Rojo oscuro",
    '§5': "Púrpura",
    '§6': "Oro",
    '§7': "Gris claro",
    '§8': "Gris oscuro",
    '§9': "Azul claro",
    '§a': "Verde claro",
    '§b': "Aguamarina",
    '§c': "Rojo Claro",
    '§d': "Rosa",
    '§e': "Amarillo",
    '§f': "Blanco",
}

hostile_mobs = {
    "bogged": "Enfangado",
    "breeze": "Brisa",
    "blaze": "Blaze",
    "cave_spider": "Araña de cueva",
    "creaking": "Creaking",
    "creeper": "Creeper",
    "drowned": "Ahogado",
    "enderman": "Enderman",
    "endermite": "Endermite",
    "evocation_illager": "Evocador",
    "ghast": "Ghast",
    "guardian": "Guardian",
    "hoglin": "Hoglin",
    "husk": "Husk",
    "magma_cube": "Cubo de magma",
    "piglin": "Piglin",
    "piglin_brute": "Piglin Bruto",
    "pillager": "Pillager",
    "phantom": "Fantasma",
    "ravager": "Ravager",
    "shulker": "Shulker",
    "silverfish": "Silverfish",
    "skeleton": "Esqueleto",
    "slime": "Slime",
    "spider": "Araña",
    "stray": "Stray",
    "vex": "Vex",
    "vindicator": "Vindicador",
    "witch": "Bruja",
    "wither_skeleton": "Esqueleto Wither",
    "zoglin": "Zoglin",
    "zombie": "Zombie",
    "zombie_villager": "Aldeano Zombificado",
    "elder_guardian": "Guardia anciano",
}

pacific_mobs = {
    "allay": "Allay",
    "armadillo": "Armadillo",
    "axolotl": "Ajolote",
    "bat": "Murciélago",
    "bee": "Abeja",
    "camel": "Camello",
    "cat": "Gato",
    "chicken": "Gallina",
    "cow": "Vaca",
    "donkey": "Burro",
    "fox": "Zorro",
    "frog": "Rana",
    "goat": "Cabra",
    "horse": "Caballo",
    "llama": "Llama",
    "mooshroom": "Chapivaca",
    "mule": "Mula",
    "panda": "Panda",
    "parrot": "Loro",
    "pig": "Cerdo",
    "rabbit": "Conejo",
    "sheep": "Oveja",
    "sniffer": "Sniffer",
    "strider": "Strider",
    "turtle": "Tortuga",
    "wolf": "Lobo"
}

special_mobs = {
    "lightning_bolt": "Rayo",
    "wind_charge_projectile": "Proyectil de carga de viento",
    "wither": "Wither",
    "warden": "Warden",
}

effects = {
    "absorption": "Absorción",
    "fire_resistance": "Resistencia al fuego",
    "haste": "Apuro",
    "instant_health": "Salud instantánea",
    "jump_boost": "Salto mejorado",
    "night_vision": "Visión nocturna",
    "regeneration": "Regeneración",
    "resistance": "Resistencia",
    "saturation": "Saturación",
    "slow_falling": "Caída lenta",
    "speed": "Velocidad",
    "strength": "Fuerza",
    "water_breathing": "Respiración acuática",
    "blindness": "Ceguera",
    "darkness": "Oscuridad",
    "hunger": "Hambre",
    "infested": "Infestado",
    "levitation": "Levitación",
    "mining_fatigue": "Fatiga de minería",
    "nausea": "Náusea",
    "poison": "Veneno",
    "slowness": "Lentitud",
    "weakness": "Debilidad",
    "wither": "Wither"
}

nice_effects = {
    "absorption": "Absorción",
    "fire_resistance": "Resistencia al fuego",
    "haste": "Apuro",
    "instant_health": "Salud instantánea",
    "jump_boost": "Salto mejorado",
    "night_vision": "Visión nocturna",
    "regeneration": "Regeneración",
    "resistance": "Resistencia",
    "saturation": "Saturación",
    "slow_falling": "Caída lenta",
    "speed": "Velocidad",
    "strength": "Fuerza",
    "water_breathing": "Respiración acuática"
}

bad_effects = {
    "blindness": "Ceguera",
    "darkness": "Oscuridad",
    "hunger": "Hambre",
    "infested": "Infestado",
    "levitation": "Levitación",
    "mining_fatigue": "Fatiga de minería",
    "nausea": "Náusea",
    "poison": "Veneno",
    "slowness": "Lentitud",
    "weakness": "Debilidad",
    "wither": "Wither"
}

random_events = [
    {
        "name": "Spawn de Mob Hostil",
        "command": "spawn_mob_at_player",
        "args": {"mob_dict": hostile_mobs, "player_name": "random", "username": "Herobrine"}
    },
    {
        "name": "Teletransporte aleatorio",
        "command": "teleport_player",
        "args": {"player_name": "random", "username": "Cronometro"}
    },
    {
        "name": "Efecto de poción aleatorio",
        "command": "roulette_effect",
        "args": {"player_name": "random", "username": "Cronometro"}
    }
]